### ISSUE TITLE
Replace current repo contents with paulrberg solidity template

### ISSUE THREAD

**Issue by wildmolasses** [sunday-club/learning-uniswap#3]
This will give us an automatic awesome development framework for using solidity and ethersjs.

steps:
- first, pull down our repository to your machine via `git clone https://github.com/sunday-club/learning-uniswap`
- now check out the template we're going to use at https://github.com/paulrberg/solidity-template
- clone it locally to your machine via `git clone https://github.com/paulrberg/solidity-template`
- put the contents of the directory into our learning-uniswap repository (so at the root level of the repository we should see a hardhat.config.ts, a package.json, a contracts folder, etc)
- create a new branch called `solidity-template` on learning-uniswap via `git checkout -b solidity-template` (have to do it from the learning-uniswap project folder)
- add all the solidity template stuff to git's stage via `git add .`
- commit via `git commit -m "adding solidity template"`
- push here via `git push origin HEAD`
- open a new pull request on this repository

**Comment by Scapestudio** [comment]
Hi Ed
I'm having some kind of annoying issue here. When try to push i get this error 
> git push origin HEAD
remote: Permission to sunday-club/learning-uniswap.git denied to Scapestudio.
fatal: unable to access 'https://github.com/sunday-club/learning-uniswap/': The requested URL returned error: 403

I've already read all the topic about it on stackoverflow and google, tried to recreate a token passcode on github but it doesn't work as well. 

My step for this were
- Pull down the   git clone git clone https://github.com/sunday-club/learning-uniswap in to my Development folder. 
- Opening the of learning-uniswap in vscode  and than from the terminal inside vscode I've cloned the solidity template with git clone https://github.com/paulrberg/solidity-template
- create a new branch with  git checkout -b solidity-template
-commit via  git commit -m "adding solidity template"
And when I push that error appear. I dont the problem is in my workflow but is somewhere in my password access or on the keychain access, even if I've update the git.com file in the with the new token credential.

I'm sorry this is very annoying, yesterday I've stayed up until late at night but can't solve it

**Comment by wildmolasses** [comment]
Hey Andrea, you need to change your remote url to remove the forward slash at the end. you can try:
`git remote set-url origin https://github.com/sunday-club/learning-uniswap.git`

**Comment by Scapestudio** [comment]
Ed I'm sorry to bother you but it still doesn't work this is my command line, it looks that changes the origin url but the error still appear. Also now VScose when I push is asking for my guthup Username (Scapestudio) and Password (which is the Token). When I put those in thats the error that appear.

> git remote set-url origin https://github.com/sunday-club/learning-uniswap.git
> git remote -v
origin  https://github.com/sunday-club/learning-uniswap.git (fetch)
origin  https://github.com/sunday-club/learning-uniswap.git (push)
> git push origin HEAD
remote: Permission to sunday-club/learning-uniswap.git denied to Scapestudio.
fatal: unable to access 'https://github.com/sunday-club/learning-uniswap.git/': The requested URL returned error: 403

**Comment by Scapestudio** [comment]
P.S. I'm calling all of this from the /Development/learning-uniswap  solidity-template     as a branch

**Comment by Scapestudio** [comment]
now ive this problem

> git push origin HEAD
info: please complete authentication in your browser...
fatal: Could not create new item [0xffff1598]
To https://github.com/sunday-club/learning-uniswap
 ! [rejected]        HEAD -> solidity-template (non-fast-forward)
error: failed to push some refs to 'https://github.com/sunday-club/learning-uniswap'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by wildmolasses** [comment]
Closing this issue since it was done
